[package]
name = "notifier"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
lettre = { version = "0.11", default-features = false, features = ["builder", "smtp-transport", "tokio1-rustls-tls", "hostname"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
