[package]
name = "telemetry"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
axum = "0.8"
opentelemetry = "0.33"
opentelemetry-otlp = { version = "0.33", default-features = false, features = ["grpc-tonic", "trace"] }
opentelemetry-stdout = { version = "0.33", default-features = false, features = ["trace"] }
opentelemetry_sdk = { version = "0.33", features = ["rt-tokio"] }
tracing = "0.1"
tracing-opentelemetry = "0.34"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid = { version = "1", features = ["v7"] }
